[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
rsa = "0.9.6"
rand = "0.8.5"
argon2 = "0.5.3"
dotenv = "0.15"
diesel = { version = "2.2.0", features = ["postgres"] }